/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ProfilePage';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/button/button';
import * as import14 from 'ionic-angular/components/menu/menu-toggle';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from 'ionic-angular/components/icon/icon';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from 'ionic-angular/components/label/label';
import * as import22 from 'ionic-angular/components/datetime/datetime';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import38 from 'ionic-angular/components/picker/picker';
import * as import39 from '@angular/forms/src/directives/control_value_accessor';
var renderType_ProfilePage_Host:import0.RenderComponentType = (null as any);
class _View_ProfilePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ProfilePage_0_4:import3.ProfilePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProfilePage_Host0,renderType_ProfilePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ProfilePage',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProfilePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProfilePage_0_4 = new import3.ProfilePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._ProfilePage_0_4,[],compView_0);
    compView_0.create(this._ProfilePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfilePage) && (0 === requestNodeIndex))) { return this._ProfilePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ProfilePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ProfilePage_Host === (null as any))) { (renderType_ProfilePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ProfilePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProfilePageNgFactory:import10.ComponentFactory<import3.ProfilePage> = new import10.ComponentFactory<import3.ProfilePage>('ProfilePage',viewFactory_ProfilePage_Host0,import3.ProfilePage);
const styles_ProfilePage:any[] = [];
var renderType_ProfilePage:import0.RenderComponentType = (null as any);
class _View_ProfilePage0 extends import1.AppView<import3.ProfilePage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import13.Button;
  _MenuToggle_4_5:import14.MenuToggle;
  _ToolbarItem_4_6:import15.ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import17.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import18.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _ToolbarItem_12_3:import15.ToolbarItem;
  _query_Button_12_0:import16.QueryList<any>;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Button_14_4:import13.Button;
  _text_15:any;
  _el_16:any;
  _Icon_16_3:import17.Icon;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Content_22_4:import19.Content;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _Button_33_4:import13.Button;
  _MenuToggle_33_5:import14.MenuToggle;
  _ToolbarItem_33_6:import15.ToolbarItem;
  _query_Button_33_0:import16.QueryList<any>;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _Item_36_4:import20.Item;
  _ItemContent_36_5:import20.ItemContent;
  _query_Label_36_0:import16.QueryList<any>;
  _query_Button_36_1:import16.QueryList<any>;
  _query_Icon_36_2:import16.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Label_38_3:import21.Label;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _DateTime_41_4:import22.DateTime;
  __NG_VALUE_ACCESSOR_41_5:any[];
  _text_42:any;
  _text_43:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProfilePage0,renderType_ProfilePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_41_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_41_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_41_5 = [this._DateTime_41_4]); }
    return this.__NG_VALUE_ACCESSOR_41_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import28.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import13.Button('','',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import14.MenuToggle(this.parentInjector.get(import29.MenuController),new import24.ElementRef(this._el_4),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import15.ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import17.Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import30.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import18.ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n            Profil\n        ',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_12,'end','');
    this._ToolbarItem_12_3 = new import15.ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_12_0 = new import16.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'ion-button','');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import28.viewFactory_Button0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Button_14_4 = new import13.Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_14),this.renderer);
    this._appEl_14.initComponent(this._Button_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','options');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import17.Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_14.create(this._Button_14_4,[[].concat([
        this._text_15,
        this._el_16,
        this._text_17
      ]
    )],(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([this._el_12]),
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._text_19
      ]
      )
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_22 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_22,'padding','');
    this._appEl_22 = new import2.AppElement(22,(null as any),this,this._el_22);
    var compView_22:any = import31.viewFactory_Content0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Content_22_4 = new import19.Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_22.initComponent(this._Content_22_4,[],compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Ionic profile',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n        If you get lost, the ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'href','http://ionicframework.com/docs/v2');
    this._text_30 = this.renderer.createText(this._el_29,'docs',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,' will show you the way.\n    ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_33,'ion-button','');
    this.renderer.setElementAttribute(this._el_33,'menuToggle','');
    this.renderer.setElementAttribute(this._el_33,'secondary','');
    this._appEl_33 = new import2.AppElement(33,22,this,this._el_33);
    var compView_33:any = import28.viewFactory_Button0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Button_33_4 = new import13.Button('','',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_33),this.renderer);
    this._MenuToggle_33_5 = new import14.MenuToggle(this.parentInjector.get(import29.MenuController),new import24.ElementRef(this._el_33),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import12.Navbar,(null as any)));
    this._ToolbarItem_33_6 = new import15.ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_33),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this.parentInjector.get(import12.Navbar,(null as any)));
    this._query_Button_33_0 = new import16.QueryList<any>();
    this._appEl_33.initComponent(this._Button_33_4,[],compView_33);
    this._text_34 = this.renderer.createText((null as any),'Toggle Menu',(null as any));
    compView_33.create(this._Button_33_4,[[].concat([this._text_34])],(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','item item-block');
    this._appEl_36 = new import2.AppElement(36,22,this,this._el_36);
    var compView_36:any = import35.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Item_36_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_36),this.renderer);
    this._ItemContent_36_5 = new import20.ItemContent();
    this._query_Label_36_0 = new import16.QueryList<any>();
    this._query_Button_36_1 = new import16.QueryList<any>();
    this._query_Icon_36_2 = new import16.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_4,[],compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_38_3 = new import21.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_38),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Start Time',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_41,'displayFormat','h:mm A');
    this.renderer.setElementAttribute(this._el_41,'pickerFormat','h mm A');
    this._appEl_41 = new import2.AppElement(41,36,this,this._el_41);
    var compView_41:any = import37.viewFactory_DateTime0(this.viewUtils,this.injector(41),this._appEl_41);
    this._DateTime_41_4 = new import22.DateTime(this.parentInjector.get(import36.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_41),this.renderer,this._Item_36_4,this.parentInjector.get(import38.PickerController,(null as any)));
    this._appEl_41.initComponent(this._DateTime_41_4,[],compView_41);
    compView_41.create(this._DateTime_41_4,[],(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_36_0.reset([this._Label_38_3]);
    this._Item_36_4.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_4,[
      [],
      [].concat([this._el_38]),
      [].concat([
        this._text_37,
        this._text_40,
        this._text_42
      ]
      ),
      [].concat([this._el_41]),
      []
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n',(null as any));
    compView_22.create(this._Content_22_4,[
      [],
      [].concat([
        this._text_23,
        this._el_24,
        this._text_26,
        this._el_27,
        this._text_32,
        this._el_33,
        this._text_35,
        this._el_36,
        this._text_43
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_41,'click',this.eventHandler(this._handle_click_41_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_41,'keyup.space',this.eventHandler(this._handle_keyup_space_41_1.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import13.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import14.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import15.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import18.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import17.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3; }
    if (((token === import13.Button) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Button_14_4; }
    if (((token === import15.ToolbarItem) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ToolbarItem_12_3; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Header_0_3; }
    if (((token === import13.Button) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Button_33_4; }
    if (((token === import14.MenuToggle) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._MenuToggle_33_5; }
    if (((token === import15.ToolbarItem) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ToolbarItem_33_6; }
    if (((token === import21.Label) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Label_38_3; }
    if (((token === import22.DateTime) && (41 === requestNodeIndex))) { return this._DateTime_41_4; }
    if (((token === import39.NG_VALUE_ACCESSOR) && (41 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_41_5; }
    if (((token === import20.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_36_4; }
    if (((token === import20.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemContent_36_5; }
    if (((token === import19.Content) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Content_22_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = 'options';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Icon_16_3.name = currVal_8;
      this._expr_8 = currVal_8;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_22_4.ngOnInit(); }
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._MenuToggle_33_5.menuToggle = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = 'h:mm A';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._DateTime_41_4.displayFormat = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = 'h mm A';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._DateTime_41_4.pickerFormat = currVal_17;
      this._expr_17 = currVal_17;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_12_0.dirty) {
        this._query_Button_12_0.reset([this._Button_14_4]);
        this._ToolbarItem_12_3._buttons = this._query_Button_12_0;
        this._query_Button_12_0.notifyOnChanges();
      }
      if (this._query_Button_33_0.dirty) {
        this._query_Button_33_0.reset([this._Button_33_4]);
        this._ToolbarItem_33_6._buttons = this._query_Button_33_0;
        this._query_Button_33_0.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset([]);
        this._Item_36_4._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset([]);
        this._Item_36_4._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_14_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_33_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_41_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_36_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_16_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_22_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_22,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = this._MenuToggle_33_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_33,'hidden',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_18:any = this._DateTime_41_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_41,'datetime-disabled',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Icon_16_3.ngOnDestroy();
    this._DateTime_41_4.ngOnDestroy();
    this._Content_22_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.openModal()) !== false);
    return (true && pd_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_33_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_41_0($event:any):boolean {
    this._appEl_41.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_41_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_41_1($event:any):boolean {
    this._appEl_41.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_41_4._keyup()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ProfilePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ProfilePage> {
  if ((renderType_ProfilePage === (null as any))) { (renderType_ProfilePage = viewUtils.createRenderComponentType('/Users/Guillaume/Documents/EPSI/ASAP/ASAP/ASAP/.tmp/pages/ProfilePage/ProfilePage.html',0,import9.ViewEncapsulation.None,styles_ProfilePage,{})); }
  return new _View_ProfilePage0(viewUtils,parentInjector,declarationEl);
}