/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'ionic-angular/components/menu/menu';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from 'ionic-angular/components/button/button';
import * as import16 from 'ionic-angular/components/menu/menu-toggle';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from 'ionic-angular/components/item/item';
import * as import23 from 'ionic-angular/components/nav/nav';
import * as import24 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import25 from 'ionic-angular/components/menu/menu-controller';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import33 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from '../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import36 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import37 from 'ionic-angular/components/app/app';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import44 from 'ionic-angular/navigation/nav-controller-base';
import * as import45 from '@angular/core/src/linker/component_factory_resolver';
import * as import46 from 'ionic-angular/transitions/transition-controller';
import * as import47 from 'ionic-angular/navigation/deep-linker';
import * as import48 from 'ionic-angular/components/menu/menu-close';
var renderType_MyApp_Host:import0.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyApp_0_4:import3.MyApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyApp_0_4 = new import3.MyApp(this.parentInjector.get(import8.Platform));
    this._appEl_0.initComponent(this._MyApp_0_4,[],compView_0);
    compView_0.create(this._MyApp_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import10.ComponentFactory<import3.MyApp> = new import10.ComponentFactory<import3.MyApp>('ng-component',viewFactory_MyApp_Host0,import3.MyApp);
const styles_MyApp:any[] = [];
var renderType_MyApp:import0.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import3.MyApp> {
  _viewQuery_Nav_0:import11.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Menu_0_4:import12.Menu;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import13.Header;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Toolbar_4_4:import13.Toolbar;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ToolbarTitle_6_4:import14.ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Button_9_4:import15.Button;
  _MenuToggle_9_5:import16.MenuToggle;
  _ToolbarItem_9_6:import17.ToolbarItem;
  _query_Button_9_0:import11.QueryList<any>;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import18.Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _Content_16_4:import19.Content;
  _text_17:any;
  _el_18:any;
  _List_18_3:import20.List;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import21.NgFor;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Item_22_4:import22.Item;
  _query_Label_22_0:import11.QueryList<any>;
  _query_Button_22_1:import11.QueryList<any>;
  _query_Icon_22_2:import11.QueryList<any>;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import22.Item;
  _ItemContent_24_5:import22.ItemContent;
  _query_Label_24_0:import11.QueryList<any>;
  _query_Button_24_1:import11.QueryList<any>;
  _query_Icon_24_2:import11.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Icon_26_3:import18.Icon;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _Nav_36_4:import23.Nav;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import24.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import12.Menu(this.parentInjector.get(import25.MenuController),new import26.ElementRef(this._el_0),this.parentInjector.get(import27.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import30.GestureController));
    this._appEl_0.initComponent(this._Menu_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_2_3 = new import13.Header(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','toolbar');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_Toolbar0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Toolbar_4_4 = new import13.Toolbar(this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Toolbar_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import14.ToolbarTitle(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_6),this.renderer,this._Toolbar_4_4,this.parentInjector.get(import34.Navbar,(null as any)));
    this._appEl_6.initComponent(this._ToolbarTitle_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_6.create(this._ToolbarTitle_6_4,[[].concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'end','');
    this.renderer.setElementAttribute(this._el_9,'ion-button','');
    this.renderer.setElementAttribute(this._el_9,'menuToggle','');
    this._appEl_9 = new import2.AppElement(9,4,this,this._el_9);
    var compView_9:any = import35.viewFactory_Button0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Button_9_4 = new import15.Button('','',this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_9),this.renderer);
    this._MenuToggle_9_5 = new import16.MenuToggle(this.parentInjector.get(import25.MenuController),new import26.ElementRef(this._el_9),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import34.Navbar,(null as any)));
    this._ToolbarItem_9_6 = new import17.ToolbarItem(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_9),this.renderer,this._Toolbar_4_4,this.parentInjector.get(import34.Navbar,(null as any)));
    this._query_Button_9_0 = new import11.QueryList<any>();
    this._appEl_9.initComponent(this._Button_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','md-close');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import18.Icon(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_9.create(this._Button_9_4,[[].concat([
        this._text_10,
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_4.create(this._Toolbar_4_4,[
      [].concat([this._el_9]),
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_16 = new import2.AppElement(16,0,this,this._el_16);
    var compView_16:any = import36.viewFactory_Content0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Content_16_4 = new import19.Content(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import37.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_16.initComponent(this._Content_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_18,'id','main-menu');
    this._List_18_3 = new import20.List(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_20 = new import2.AppElement(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import39.TemplateRef_(this._appEl_20,viewFactory_MyApp1);
    this._NgFor_20_6 = new import21.NgFor(this._appEl_20.vcRef,this._TemplateRef_20_5,this.parentInjector.get(import40.IterableDiffers),this.ref);
    this._text_21 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_18,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item');
    this._appEl_22 = new import2.AppElement(22,18,this,this._el_22);
    var compView_22:any = import41.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import22.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_22),this.renderer);
    this._query_Label_22_0 = new import11.QueryList<any>();
    this._query_Button_22_1 = new import11.QueryList<any>();
    this._query_Icon_22_2 = new import11.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4,[],compView_22);
    this._query_Label_22_0.reset([]);
    this._Item_22_4.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4,[
      [],
      [],
      [],
      [],
      []
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this.renderer.setElementAttribute(this._el_24,'ion-item','');
    this._appEl_24 = new import2.AppElement(24,18,this,this._el_24);
    var compView_24:any = import41.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import22.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import22.ItemContent();
    this._query_Label_24_0 = new import11.QueryList<any>();
    this._query_Button_24_1 = new import11.QueryList<any>();
    this._query_Icon_24_2 = new import11.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','ios-unlock');
    this.renderer.setElementAttribute(this._el_26,'role','img');
    this._Icon_26_3 = new import18.Icon(this.parentInjector.get(import27.Config),new import26.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Déconnexion',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_24_0.reset([]);
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      [],
      [],
      [].concat([
        this._text_25,
        this._el_26,
        this._text_27,
        this._el_28,
        this._text_30
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_16.create(this._Content_16_4,[
      [],
      [].concat([
        this._text_17,
        this._el_18,
        this._text_32
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n\n',(null as any));
      compView_0.create(this._Menu_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_15,
        this._el_16,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_36 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_36,'swipeBackEnabled','false');
    this._appEl_36 = new import2.AppElement(36,(null as any),this,this._el_36);
    var compView_36:any = import43.viewFactory_Nav0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Nav_36_4 = new import23.Nav(this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import44.NavControllerBase,(null as any)),this.parentInjector.get(import37.App),this.parentInjector.get(import27.Config),this.parentInjector.get(import28.Keyboard),new import26.ElementRef(this._el_36),this.parentInjector.get(import29.NgZone),this.renderer,this.parentInjector.get(import45.ComponentFactoryResolver),this.parentInjector.get(import30.GestureController),this.parentInjector.get(import46.TransitionController),this.parentInjector.get(import47.DeepLinker,(null as any)));
    this._appEl_36.initComponent(this._Nav_36_4,[],compView_36);
    compView_36.create(this._Nav_36_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_36_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4; }
    if (((token === import18.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3; }
    if (((token === import15.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Button_9_4; }
    if (((token === import16.MenuToggle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MenuToggle_9_5; }
    if (((token === import17.ToolbarItem) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarItem_9_6; }
    if (((token === import13.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Toolbar_4_4; }
    if (((token === import13.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Header_2_3; }
    if (((token === import39.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import21.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6; }
    if (((token === import22.Item) && (22 === requestNodeIndex))) { return this._Item_22_4; }
    if (((token === import18.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3; }
    if (((token === import22.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_24_4; }
    if (((token === import22.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_24_5; }
    if (((token === import20.List) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._List_18_3; }
    if (((token === import19.Content) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Content_16_4; }
    if (((token === import12.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Menu_0_4; }
    if (((token === import23.Nav) && (36 === requestNodeIndex))) { return this._Nav_36_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_36_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_0_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_0_4.ngOnInit(); }
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_9_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'md-close';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_11_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_16_4.ngOnInit(); }
    changes = (null as any);
    const currVal_8:any = this.context.pages;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgFor_20_6.ngForOf = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._NgFor_20_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_20_6.ngDoCheck(); }
    const currVal_9:any = 'ios-unlock';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_26_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Nav_36_4.root = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Nav_36_4.swipeBackEnabled = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_9_0.dirty) {
        this._query_Button_9_0.reset([this._Button_9_4]);
        this._ToolbarItem_9_6._buttons = this._query_Button_9_0;
        this._query_Button_9_0.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset([]);
        this._Item_22_4._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset([]);
        this._Item_22_4._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset([]);
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset([this._Icon_26_3]);
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_22_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Toolbar_4_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_9_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_9,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_11_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_16_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_16,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._Icon_26_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_26,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_36_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_11_3.ngOnDestroy();
    this._Icon_26_3.ngOnDestroy();
    this._Content_16_4.ngOnDestroy();
    this._Menu_0_4.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_9_5.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MyApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('/Users/Guillaume/Documents/EPSI/ASAP/ASAP/ASAP/.tmp/app/app.html',0,import9.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import22.Item;
  _ItemContent_0_5:import22.ItemContent;
  _MenuClose_0_6:import48.MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import18.Icon;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import22.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import22.ItemContent();
    this._MenuClose_0_6 = new import48.MenuClose(this.parent.parentInjector.get(import25.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import18.Icon(this.parent.parentInjector.get(import27.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_3,
        this._el_4,
        this._text_6
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import22.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4; }
    if (((token === import22.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5; }
    if (((token === import48.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.iconname,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}